version: "3.7"

services: 
  postgres:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_USER=fyko
      - POSTGRES_PASSWORD=doctordoctor
    ports: 
      - 5432:5432
    # expose:
    #   - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  graphql-engine:
    restart: unless-stopped
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://fyko:doctordoctor@postgres:5432/shortener
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

volumes:
  pg_data: