version: "2.1"

services: 
  redis:
    image: "redis:5-alpine"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
    ports: 
      - 6379:6379
    expose: 
      - 6379
    volumes:
      - "redis_data:/data"
  postgres:
    restart: unless-stopped
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_USER=fyko
      - POSTGRES_PASSWORD=doctordoctor
    ports: 
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis_data: